apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
  - ./prometheus.yaml
  - ./grafana.yaml
  - ./jaeger.yaml
  - ./kiali.yaml

configMapGenerator:
  - name: istio-flagger-grafana-dashboards
    files:
      - dashboards/flagger/appmesh.json
      - dashboards/flagger/envoy.json
      - dashboards/flagger/istio.json
