apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k6-operator-system

resources:
  - k6.yaml

configMapGenerator:
  - name: productpage-loadtest
    files:
      - productpage.js
