apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-system
  namespace: booking
spec:
  interval: 10m0s
  path: ./apps/booking
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
