apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-system
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  path: ./infra-resources/istio/system
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: istio-version
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-gateway
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  dependsOn:
    - name: istio-system
  path: ./infra-resources/istio/gateway
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-telemetry
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  dependsOn:
    - name: istio-system
  path: ./infra-resources/istio/telemetry
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
