apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: k6-system
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 15m
  path: ./infra-resources/k6/default
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
