apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    istio-injection: enabled
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flagger-loadtester
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infra-resources/test/flagger-loadtester
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: k6-loadtester
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infra-resources/test/k6-loadtester
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
