---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flagger-loadtester
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: istio-system
  path: ./apps/loadtester
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
